version: "3.4"

services:
  goplaces-server:
    container_name: server_container
    build: .
    command: npm start
    depends_on:
      - mongodb
      - cassandradb
    ports:
      - 3000:3000
    links:
      - mongodb
      - cassandradb    
  mongodb:
    container_name: mongodb_container
    image: mongo:latest
    ports:
      - 27017:27017
  cassandradb:
    container_name: cassandra_container
    image: cassandra:latest
    
    ports:
      - 9042:9042
    volumes:
      - ./database:/var/lib/cassandra  
    
  
  
    

