version: "3.4"

services:
  goplaces-server:
    container_name: server_container
    build: .
    command: npm start
    depends_on:
      - mongodb
    volumes:
      - .:/app
    ports:
      - 3000:3000
    links:
      - mongodb
  mongodb:
    container_name: mongodb_container
    image: mongo:latest
    ports:
      - 27017:27017 
    

